services:
  pybase:
    container_name: pybase

    image: pybase

    build:
      context: .
      dockerfile: pybase.Dockerfile

    volumes:
      - .:/app

  statusaibot:
    container_name: statusaibot

    image: statusaibot

    build:
      context: .
      dockerfile: statusaibot.Dockerfile

    environment:
      PYTHONUNBUFFERED: 1
      DOCKER: "true"

    volumes:
      - .:/app